### ISSUE TITLE
[Component Implementation: Layout] Divider

### ISSUE THREAD

**Issue by ernestoresende** [EightSystems/design-system#48]
### Description
Helper layout component used to render a divider between components.

### Implementation checklist
- [x] The component was tested and is fully working in web environments, without any observable bugs and/or unexpected behavior.
- [x] The component was tested and is fully working in native environments, without any observable bugs and/or unexpected behavior.
- [x] The component API is fully documented in both the internal Storybook documentation and in-code.

**Comment by tryvin** [comment]
@ernestoresende Divider ou Spacer?

**Comment by ernestoresende** [comment]
@tryvin Divider mesmo. Equivalente a um elemento `<hr>` da web. O componente `Spacer` está no #47
