### ISSUE TITLE
[CORE] Form/TextField Component Implementation

### ISSUE THREAD

**Issue by ernestoresende** [EightSystems/design-system#5]
Checklist:

- [x] Code for the component is implemented and tested.
- [x] Documentation for the component is completed and the API is well-defined.
- [x] The component is ready to be used in production.

**Comment by tryvin** [comment]
@ernestoresende no seu storybook você colocou como `type`, `password` e `email`, só há suporte a esses dois tipos?

**Comment by ernestoresende** [comment]
Possuem mais. Vou continuar deixando os limites rigidamente tipados com `type: Proptypes.oneOf([])`, mas abrangendo pra outros types que sejam estritamente relacionados ao input de strings (texto ou numérico) como `text`, `tel`, já que alguns não fazem sentido nessa estrutura de componente (`file` e `image` por exemplo).
