### ISSUE TITLE
[Component Implementation: Feedback] ProgressRing

### ISSUE THREAD

**Issue by ernestoresende** [EightSystems/design-system#53]
### Description
Use to indicate linear progress in a ring.

### Implementation checklist
- [x] The component was tested and is fully working in web environments, without any observable bugs and/or unexpected behavior.
- [x] The component was tested and is fully working in native environments, without any observable bugs and/or unexpected behavior.
- [x] The component API is fully documented in both the internal Storybook documentation and in-code.

**Comment by tryvin** [comment]
PR: https://github.com/EightSystems/design-system/pull/67
