### ISSUE TITLE
[CORE] Molecule/PaymentStatus Component Implementation

### ISSUE THREAD

**Issue by ernestoresende** [EightSystems/design-system#8]
Checklist:

- [x] Code for the component is implemented and tested.
- [x] Documentation for the component is completed and the API is well-defined.
- [x] The component is ready to be used in production.

**Comment by tryvin** [comment]
@ernestoresende talvez trocar o ícone de Pending para algo como. uma ampulheta, não sei, essa exclamação remonta a um error o que não é o caso
